Add option to configute kernel module parameters
stuvusIT/zfs-storage pull request #20
Opened 2018-02-28 21:56 UTC by SlothOfAnarchy

2018-02-28 22:45 UTC, ghost approved these changes

2018-02-28 22:45 UTC, schuppentier commented on README.md
> +| `zfs_kernel_module_parameters` |        `{}`         | Dict containing ZFS kernel module options to be set in `/etc/modprobe.d/zfs.conf`/.]
Please remove the ]

2018-02-28 22:45 UTC, schuppentier commented on templates/zfs.conf.j2
> +#{{ ansible_managed }}
Can you add a blank between the hash and the comment?

2018-02-28 22:45 UTC, schuppentier commented on templates/zfs.conf.j2
> +options zfs{% for key,value in zfs_kernel_module_parameters.iteritems() %} {{ key }}={{ value }}{% endfor %}
Beautiful :)

2018-02-28 22:46 UTC, ghost submitted a review, later dismissed
Wrong button (again)

2018-03-04 11:10 UTC, SlothOfAnarchy commented
@dasJ please rereview.

2018-03-04 14:49 UTC, dasJ requested changes
There's still the `]`

2018-03-04 14:52 UTC, dasJ approved these changes

2018-03-04 14:52 UTC, SlothOfAnarchy commented
Sorry, now it's gone.
Overlooked it and thought you meant the `/` I removed before...

2018-03-04 14:52 UTC, merged